In [54]:
import numpy as np
import pandas as pd
from setup import *

In [55]:
result_file = "results.csv"

In [60]:
group_cols = ['Model Type','Distribution','Time Size']
metric_cols = ['train_nll_loss','test_nll_loss',
                 'train_mae','test_mae',
                 'train_mape','test_mape',
                 'train_mpiw','test_mpiw',
                 'train_picp','test_picp']
table_cols = ['Model','weight_decay','dropout','val_nll_loss','test_nll_loss',
                 'test_mpiw',
                 'test_picp',
                 'test_mae',
                 'test_mape']

## Before

In [101]:
dfb = pd.read_csv(project_dir+"results/R1_rail_190801-200301_200302-200315/"+result_file)

In [100]:
# top model by category
dfb = dfb.sort_values(by='val_nll_loss')
dfb.groupby(group_cols).head(1)[group_cols+table_cols+['n_head']].sort_values(group_cols)


# dfb.loc[dfb.groupby(group_cols)['val_nll_loss'].idxmin()][group_cols+table_cols].sort_values(group_cols)

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape,n_head
72,GAT,laplace,1,0,0.0001,0.2,467.94,468.35,45.296878,0.976941,8.43,0.20,2.0
56,GAT,norm,1,0,0.0001,0.2,477.20,469.92,41.451949,0.963775,8.43,0.20,2.0
41,GAT,norm_homo,1,1,0.0010,0.2,681.10,683.47,116.015041,0.990980,9.08,0.21,2.0
101,GAT,norm_homo0.25,1,2,0.1000,0.1,703.93,695.08,36.482475,0.932715,8.24,0.19,2.0
86,GAT,norm_homo0.5,1,1,0.0500,0.1,623.00,635.24,65.208800,0.974595,8.71,0.21,2.0
43,GAT,poisson,1,0,0.0001,0.2,569.82,562.35,18.260262,0.811638,8.45,0.20,2.0
67,GAT,tnorm,1,3,0.1000,0.2,471.42,464.40,41.604579,0.966794,8.47,0.20,2.0
22,GCN,laplace,1,6,0.0100,0.5,468.40,463.77,46.494051,0.973850,8.16,0.19,NaN
7,GCN,norm,1,7,0.1000,0.5,471.86,464.53,40.604212,0.964975,8.60,0.20,NaN
32,GCN,norm_homo,1,0,0.0001,0.2,678.78,678.89,115.695778,0.993162,7.99,0.19,NaN
97,GCN,norm_homo0.25,1,0,0.0100,0.1,665.54,735.13,36.841172,0.930696,8.47,0.20,NaN
80,GCN,norm_homo0.5,1,0,0.0100,0.1,616.12,620.34,65.092133,0.976869,8.06,0.19,NaN
26,GCN,poisson,1,2,0.0100,0.2,557.13,520.43,18.463078,0.843208,7.54,0.18,NaN
12,GCN,tnorm,1,4,0.0001,0.5,470.08,461.43,42.248679,0.957156,8.17,0.19,NaN

In [71]:
dfb[((dfb['Model Type']=='GCN')&(dfb['Distribution']=='norm'))].sort_values(by='val_nll_loss').head()[group_cols+table_cols]

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
7,GCN,norm,1,7,0.1000,0.5,471.86,464.53,40.604212,0.964975,8.60,0.20
5,GCN,norm,1,5,0.0010,0.5,475.96,466.91,41.687492,0.957083,8.24,0.19
4,GCN,norm,1,4,0.0001,0.5,476.52,467.77,41.794586,0.953264,8.08,0.19
6,GCN,norm,1,6,0.0100,0.5,477.54,461.48,41.562667,0.961429,8.01,0.19
3,GCN,norm,1,3,0.1000,0.2,491.52,461.13,39.190873,0.959593,8.18,0.19

In [72]:
# top 5 by val nll loss (for ensembling)
dfb[((dfb['Model Type']=='GAT')&(dfb['Distribution']=='norm'))].sort_values(by='val_nll_loss').head(5)[group_cols+table_cols]

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
56,GAT,norm,1,0,0.0001,0.2,477.20,469.92,41.451949,0.963775,8.43,0.20
59,GAT,norm,1,3,0.1000,0.2,477.99,469.75,46.740211,0.971686,7.82,0.18
57,GAT,norm,1,1,0.0010,0.2,481.42,472.21,40.606422,0.950082,8.51,0.20
60,GAT,norm,1,4,0.0001,0.5,481.42,471.70,49.630162,0.973468,8.04,0.19
62,GAT,norm,1,6,0.0100,0.5,485.46,473.33,45.842527,0.968249,8.51,0.20

In [70]:
dfb.groupby(['Model Type','Distribution','Time Size']).count()['Lookback']

Model Type  Distribution  Time Size
GAT         laplace       1            8
            norm          1            8
            norm_homo     1            8
            poisson       1            8
            tnorm         1            8
GCN         laplace       1            8
            norm          1            8
            norm_homo     1            8
            poisson       1            8
            tnorm         1            8
Name: Lookback, dtype: int64

## TNC Dataset

In [104]:
dfbc = pd.read_csv(project_dir+"results/R1_census_190801-200301_200302-200315/"+result_file)

In [109]:
# top model by category
dfbc = dfbc.sort_values(by='val_nll_loss')
dfbc.groupby(group_cols).head(2)[group_cols+table_cols+['n_head']].sort_values(group_cols)


# dfbc.loc[dfbc.groupby(group_cols)['val_nll_loss'].idxmin()][group_cols+table_cols].sort_values(group_cols)

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape,n_head
35,GAT,laplace,1,2,0.10,0.1,191.58,189.52,36.077485,0.965095,6.16,0.27,2.0
40,GAT,laplace,1,6,0.10,0.3,191.83,188.63,37.968842,0.975258,6.25,0.27,2.0
19,GAT,norm,1,1,0.05,0.1,193.25,188.28,31.428107,0.956621,6.07,0.26,2.0
17,GAT,norm,1,0,0.01,0.1,193.84,190.27,31.369116,0.950938,6.61,0.29,2.0
7,GAT,norm_homo0.5,1,4,0.01,0.3,229.24,230.74,43.260507,0.968959,6.52,0.28,2.0
9,GAT,norm_homo0.5,1,5,0.05,0.3,229.25,230.13,43.000693,0.970063,6.44,0.28,2.0
63,GAT,poisson,1,2,0.10,0.1,216.87,214.89,15.619755,0.819501,6.06,0.26,2.0
58,GAT,poisson,1,0,0.01,0.1,217.10,215.04,15.385234,0.815800,5.93,0.26,2.0
43,GAT,tnorm,1,0,0.01,0.1,188.86,185.96,32.538952,0.957043,6.55,0.28,2.0
52,GAT,tnorm,1,5,0.05,0.3,189.78,185.94,33.006640,0.956134,6.52,0.28,2.0
61,GCN,laplace,1,3,0.50,0.1,189.46,187.09,34.116010,0.964641,5.81,0.25,NaN
65,GCN,laplace,1,6,0.10,0.3,190.37,187.33,33.472128,0.959251,5.80,0.25,NaN
25,GCN,norm,1,4,0.01,0.3,194.20,187.58,27.318389,0.932755,5.80,0.25,NaN
22,GCN,norm,1,3,0.50,0.1,194.75,184.85,29.214599,0.949575,5.80,0.25,NaN
4,GCN,norm_homo0.5,1,1,0.05,0.1,226.05,225.62,42.628443,0.977076,5.81,0.25,NaN
6,GCN,norm_homo0.5,1,2,0.10,0.1,226.15,225.59,42.709288,0.976979,5.82,0.25,NaN
75,GCN,poisson,1,3,0.50,0.1,207.34,211.90,15.530578,0.827197,5.81,0.25,NaN
77,GCN,poisson,1,5,0.05,0.3,209.16,213.37,15.333215,0.821060,5.89,0.26,NaN
44,GCN,tnorm,1,3,0.50,0.1,187.82,182.88,30.625598,0.952497,6.06,0.26,NaN
53,GCN,tnorm,1,7,0.50,0.3,189.47,183.09,32.479040,0.961394,6.04,0.26,NaN

In [106]:
dfbc[((dfbc['Model Type']=='GCN')&(dfbc['Distribution']=='norm'))].sort_values(by='val_nll_loss').head()[group_cols+table_cols]

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
25,GCN,norm,1,4,0.01,0.3,194.20,187.58,27.318389,0.932755,5.80,0.25
22,GCN,norm,1,3,0.50,0.1,194.75,184.85,29.214599,0.949575,5.80,0.25
31,GCN,norm,1,7,0.50,0.3,195.13,186.78,30.947604,0.949445,5.99,0.26
29,GCN,norm,1,6,0.10,0.3,197.05,185.96,28.037611,0.940418,5.72,0.25
27,GCN,norm,1,5,0.05,0.3,199.89,187.82,27.995190,0.931651,5.90,0.26

In [107]:
dfbc[((dfbc['Model Type']=='GAT')&(dfbc['Distribution']=='norm'))].sort_values(by='val_nll_loss').head(5)[group_cols+table_cols]

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
19,GAT,norm,1,1,0.05,0.1,193.25,188.28,31.428107,0.956621,6.07,0.26
17,GAT,norm,1,0,0.01,0.1,193.84,190.27,31.369116,0.950938,6.61,0.29
21,GAT,norm,1,2,0.10,0.1,194.45,188.26,30.144408,0.953179,6.09,0.26
23,GAT,norm,1,3,0.50,0.1,194.74,190.40,33.922481,0.956296,6.72,0.29
26,GAT,norm,1,5,0.05,0.3,195.25,190.39,32.418034,0.953958,6.60,0.29

In [108]:
dfbc.groupby(['Model Type','Distribution','Time Size']).count()['Lookback']

Model Type  Distribution  Time Size
GAT         laplace       1            8
            norm          1            8
            norm_homo0.5  1            8
            poisson       1            8
            tnorm         1            8
GCN         laplace       1            8
            norm          1            8
            norm_homo0.5  1            8
            poisson       1            8
            tnorm         1            8
Name: Lookback, dtype: int64

## After

In [62]:
dfa = pd.read_csv(project_dir+"results/R1_200316-201017_201018-201031/"+result_file)

In [63]:
# top models by model category
dfa = dfa.sort_values(by='val_nll_loss')
dfa.groupby(group_cols).head(1)[group_cols+table_cols].sort_values(group_cols)

,Model Type,Distribution,Time Size,Model,weight_decay,dropout,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
23,GAT,laplace,1,15,0.100,0.5,366.98,361.97,16.549881,0.970831,2.91,0.31
63,GAT,norm,1,3,0.001,0.2,362.52,359.44,13.712143,0.943117,2.94,0.31
144,GAT,norm_homo,1,14,0.100,0.5,445.46,438.95,20.354328,0.981251,2.95,0.31
30,GAT,poisson,1,6,0.100,0.2,373.24,363.30,9.782031,0.913475,2.86,0.30
155,GAT,tnorm,1,3,0.001,0.2,353.03,349.56,13.704244,0.941062,3.24,0.35
89,GCN,laplace,1,1,0.050,0.1,360.21,354.55,15.743847,0.973231,2.76,0.29
42,GCN,norm,1,2,0.100,0.1,357.34,352.49,13.418807,0.951755,2.80,0.30
124,GCN,norm_homo,1,3,0.500,0.1,442.51,439.02,20.470491,0.981560,2.92,0.31
110,GCN,poisson,1,6,0.100,0.2,365.24,355.11,9.814842,0.925277,2.76,0.29
57,GCN,tnorm,1,0,0.010,0.1,345.70,340.18,13.689870,0.956829,2.92,0.31

In [7]:
# top 5 by val nll loss (for ensembling)
dfa[((dfa['Model Type']=='GAT')&(dfa['Distribution']=='norm'))].sort_values(by='val_nll_loss').head(6)[group_cols+table_cols]

Empty DataFrame
Columns: [Distribution, Model Type, Time Size, Model, weight_decay, dropout, val_nll_loss, test_nll_loss, test_mpiw, test_picp, test_mae, test_mape]
Index: []

In [13]:
dfa[((dfa['Model Type']=='GCN')&(dfa['Distribution']=='norm'))].sort_values(by='test_nll_loss').head(6)[group_cols+table_cols]

,Model Type,Distribution,Time Size,Model,Lookback,val_nll_loss,test_nll_loss,test_mpiw,test_picp,test_mae,test_mape
1,GCN,norm,1,1,6,360.52,351.97,13.160512,0.945590,2.78,0.30
0,GCN,norm,1,0,6,361.54,355.34,12.862551,0.934170,2.81,0.30
3,GCN,norm,1,3,6,363.79,356.97,13.014518,0.935697,2.85,0.30
2,GCN,norm,1,2,6,361.39,357.17,13.456025,0.943353,2.89,0.31
4,GCN,norm,1,4,6,368.29,362.90,12.944625,0.921949,2.98,0.32
5,GCN,norm,1,5,6,374.57,364.19,12.828358,0.918712,2.98,0.32

In [53]:
dfa.groupby(['Model Type','Distribution','Time Size']).count()['Model']

Model Type  Distribution  Time Size
GAT         laplace       1            16
            norm          1            16
            norm_homo     1            16
            poisson       1            16
            tnorm         1            16
GCN         laplace       1            16
            norm          1            16
            norm_homo     1            16
            poisson       1            16
            tnorm         1            16
Name: Model, dtype: int64

In [17]:
# median of all model category
dfa.groupby(['Model Type','Distribution', 'Time Size']).median()[[
                                     'train_nll_loss','val_nll_loss','test_nll_loss',
                                     'train_mae','val_mae','test_mae',
                                     'train_mpiw','val_mpiw','test_mpiw',
                                     'train_picp','val_picp','test_picp']].round(6)

                                  train_nll_loss  val_nll_loss  test_nll_loss  \
Model Type Distribution Lookback
GAT        laplace      6                343.150       372.780        368.980
           norm         6                340.610       368.805        363.185
           poisson      6                333.050       394.835        389.260
           tnorm        6                323.930       356.115        351.560
GCN        laplace      6                344.560       373.615        368.615
           norm         6                334.525       366.040        360.035
           poisson      6                334.920       383.055        371.310
           tnorm        6                320.585       352.345        346.320

                                  train_mae  val_mae  test_mae  train_mpiw  \
Model Type Distribution Lookback
GAT        laplace      6             2.580    3.135     3.070   13.124674
           norm         6             2.540    3.070     2.970   11.854335
           poisson      6             2.390    3.200     3.160    8.646998
           tnorm        6             2.795    3.300     3.240   12.056796
GCN        laplace      6             2.610    3.185     3.130   12.232530
           norm         6             2.445    2.990     2.935   10.830162
           poisson      6             2.390    3.040     2.930    8.422302
           tnorm        6             2.700    3.230     3.110   11.220490

                                   val_mpiw  test_mpiw  train_picp  val_picp  \
Model Type Distribution Lookback
GAT        laplace      6         16.057409  15.656055    0.960238  0.954989
           norm         6         14.203904  13.903604    0.947058  0.939685
           poisson      6          9.434583   9.329843    0.931452  0.884488
           tnorm        6         14.421392  14.093191    0.948956  0.944864
GCN        laplace      6         14.765000  14.548731    0.948607  0.938418
           norm         6         13.016596  12.903588    0.937327  0.925936
           poisson      6          9.368326   9.353160    0.927423  0.895118
           tnorm        6         13.430849  13.387448    0.941985  0.934257

                                  test_picp
Model Type Distribution Lookback
GAT        laplace      6          0.951982
           norm         6          0.940270
           poisson      6          0.886343
           tnorm        6          0.940007
GCN        laplace      6          0.942735
           norm         6          0.928060
           poisson      6          0.903764
           tnorm        6          0.939444